<script lang="ts">
 import { onMount } from 'svelte'; import { fly } from 'svelte/transition'; import { api, type User } from '$lib/api';
 let user = $state<User | null>(null); onMount(async()=>{ try { user=await api('/auth/me'); } catch { window.location.assign('/login'); } });
 const enquiries=[['MCA','12 Sep 2026','Website','Application Started','Today'],['MBA','05 Sep 2026','Referral','Counselling','Yesterday']];
 const stages=[['Enquiry Submitted',true],['Counselling Completed',true],['Application In Progress',true],['Admission',false]];
</script>
<svelte:head><title>Student Dashboard | DecisionIntel</title></svelte:head>
{#if user}<div class="space-y-7 pb-10" in:fly={{y:14,duration:450}}>
 <div class="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h1 class="text-3xl font-bold text-white">Welcome back, {user.name.split(' ')[0]}</h1><p class="text-text-secondary mt-2">Track your admission journey and stay updated on your enquiries.</p></div><a href="/student/enquiries/new" class="px-5 py-3 rounded-xl bg-cta text-black font-bold text-sm shadow-[0_0_15px_rgba(242,166,43,.3)]">Start New Enquiry</a></div>
 <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5">{#each [['Active Enquiry','01','◌'],['Total Enquiries','02','▤'],['Application Status','In Progress','◷'],['Next Follow-up','18 Sep','◒']] as [label,value,icon]}<div class="bg-card border border-white/10 rounded-2xl p-5 shadow-lg"><div class="w-11 h-11 grid place-items-center rounded-xl bg-accent/15 border border-accent/25 text-accent">{icon}</div><p class="text-xs text-text-secondary uppercase tracking-wider mt-4">{label}</p><p class="text-2xl text-white font-bold mt-1">{value}</p></div>{/each}</div>
 <div class="grid lg:grid-cols-5 gap-6"><section class="lg:col-span-3 bg-card border border-white/10 rounded-2xl p-6"><div class="flex justify-between items-center mb-6"><div><h2 class="text-lg font-bold text-white">Admission Journey</h2><p class="text-sm text-text-secondary mt-1">Your current admission progress</p></div><span class="text-xs bg-accent/15 text-accent border border-accent/25 px-3 py-1 rounded-full">Application in progress</span></div><div class="grid sm:grid-cols-4 gap-3">{#each stages as [label,done], i}<div class:current={i===2} class="journey-step"><span class:done={done} class="dot">{done?'✓':i+1}</span><p>{label}</p></div>{/each}</div></section><section class="lg:col-span-2 bg-card border border-white/10 rounded-2xl p-6"><p class="text-xs uppercase tracking-wider text-accent">Next action</p><h2 class="text-lg font-bold text-white mt-2">Counselling Session</h2><p class="text-sm text-text-secondary mt-2">18 September 2026 · 11:00 AM</p><p class="text-xs text-green-400 mt-3">Confirmed</p><a class="inline-block text-sm text-accent mt-5 hover:underline" href="/student/enquiries/status">View Details →</a></section></div>
 <section class="bg-card border border-white/10 rounded-2xl p-6 overflow-x-auto"><div class="flex justify-between mb-5"><h2 class="text-lg font-bold text-white">Recent Enquiries</h2><a class="text-sm text-accent hover:underline" href="/student/enquiries">View All Enquiries</a></div><table class="w-full text-sm min-w-[650px]"><thead class="text-left text-xs uppercase tracking-wider text-text-secondary border-b border-white/10"><tr><th class="pb-3">Course / Program</th><th>Enquiry Date</th><th>Source</th><th>Status</th><th>Last Updated</th></tr></thead><tbody>{#each enquiries as item}<tr class="border-b border-white/5 text-text-secondary"><td class="py-4 font-medium text-white">{item[0]}</td><td>{item[1]}</td><td>{item[2]}</td><td><span class="px-2 py-1 rounded bg-accent/15 text-accent text-xs">{item[3]}</span></td><td>{item[4]}</td></tr>{/each}</tbody></table></section>
 <section class="bg-card border border-white/10 rounded-2xl p-6"><h2 class="text-lg font-bold text-white">Recent Activity</h2><div class="mt-4 space-y-4">{#each ['Application details updated','Counselling session scheduled','MCA enquiry submitted'] as activity,i}<div class="flex gap-3 text-sm"><span class="w-6 h-6 rounded-full bg-secondary/60 grid place-items-center text-accent">{i+1}</span><div><p class="text-white">{activity}</p><p class="text-xs text-text-secondary mt-1">{i===0?'Today':'This week'}</p></div></div>{/each}</div></section>
</div>{/if}
<style>.journey-step{position:relative;padding:1rem .75rem;border:1px solid rgba(255,255,255,.08);border-radius:1rem;color:#a7a4b4;text-align:center;font-size:.78rem}.journey-step.current{border-color:rgba(164,123,224,.55);background:rgba(164,123,224,.1);color:white}.dot{display:grid;place-items:center;width:2rem;height:2rem;margin:auto auto .6rem;border-radius:999px;background:rgba(255,255,255,.07);color:#a7a4b4}.dot.done{background:rgba(164,123,224,.35);color:white}</style>
