-- ============================================================================
-- Decision-Intel · Supabase PostgreSQL schema
-- ----------------------------------------------------------------------------
-- Project     : Decision-Intel — AI-Based Marketing Intelligence for Lead
--               Prediction and Budget Optimization in the Education Sector.
-- Target      : Supabase PostgreSQL (Postgres 13+). Safe to run on a fresh
--               Decision-Intel database. No DROP statements.
--
-- Creates exactly the 5 application tables:
--   1. users            – application users and roles (admin / manager / student)
--   2. leads            – student enquiries / marketing leads
--   3. lead_predictions – output of the trained ML conversion model
--   4. recommendations  – SHAP explanation factors + lead-action recommendation
--   5. campaigns        – marketing campaign analytics (independent table)
--
-- Security model (README for whoever wires the app to Supabase Auth):
--   * The backend (FastAPI) and the ML pipeline talk to the database either
--     through the direct DATABASE_URL connection or the Supabase service-role
--     client. Both of those BYPASS Row Level Security, so elevated operations
--     (inserting predictions/recommendations/campaigns, managing users) belong
--     in server-side code only.
--   * Only browser traffic would use the anon key, and RLS governs that.
--     RLS is therefore ENABLED on every table and denies by default.
--   * No password is stored here for Supabase Auth users; Supabase Auth manages
--     credentials in auth.users. The public.users.id should equal auth.uid()
--     when Auth is adopted (insert with the ids from auth.users).
--   * The SUPABASE_SERVICE_ROLE_KEY must never be exposed to the browser.
--
-- Intended production RLS policy set (implemented below):
--   users            – owners read/update their own row; admins manage all rows.
--   leads            – signed-in users read and insert leads; managers update.
--   lead_predictions – signed-in users read; writes only via service role.
--   recommendations  – signed-in users read; writes only via service role.
--   campaigns        – signed-in users read; writes only via service role.
-- ============================================================================

-- gen_random_uuid() is built into Postgres 13+; the extension line keeps the
-- migration working on older hosted Postgres too.
create extension if not exists pgcrypto;

-- ============================================================================
-- 1. users
-- Purpose : application users and roles.
-- NOTE    : Supabase Auth credentials live in auth.users — never here.
-- ============================================================================
create table public.users (
    id         uuid        primary key default gen_random_uuid(),
    name       text        not null,
    email      text        unique not null,
    phone      text,
    role       text        not null check (role in ('admin', 'manager', 'student')),
    created_at timestamptz not null default now()
);

-- ============================================================================
-- 2. leads
-- Purpose : student enquiries / marketing leads.
-- ============================================================================
create table public.leads (
    id            uuid        primary key default gen_random_uuid(),
    name          text        not null,
    email         text,
    phone         text,
    lead_source   text,
    lead_origin   text,
    course        text,
    city          text,
    occupation    text,
    last_activity text,
    status        text        not null default 'New',
    created_at    timestamptz not null default now()
);

-- ============================================================================
-- 3. lead_predictions
-- Purpose : output generated by the trained ML model.
-- ============================================================================
create table public.lead_predictions (
    id                     uuid        primary key default gen_random_uuid(),
    lead_id                uuid        not null references public.leads (id) on delete cascade,
    conversion_probability numeric,
    prediction             integer     check (prediction in (0, 1)),
    lead_priority          text        check (lead_priority in ('High', 'Medium', 'Low')),
    model_version          text,
    predicted_at           timestamptz not null default now()
);

-- ============================================================================
-- 4. recommendations
-- Purpose : SHAP-based explanation factors and the resulting lead action.
-- ============================================================================
create table public.recommendations (
    id               uuid        primary key default gen_random_uuid(),
    lead_id          uuid        not null references public.leads (id) on delete cascade,
    recommendation   text,
    positive_factors jsonb,
    negative_factors jsonb,
    created_at       timestamptz not null default now()
);

-- ============================================================================
-- 5. campaigns
-- Purpose : marketing campaign data for campaign performance and future
--           budget intelligence. Independent of the user/lead chain.
-- ============================================================================
create table public.campaigns (
    id          uuid        primary key default gen_random_uuid(),
    campaign_id text        not null,
    date        date,
    channel     text,
    region      text,
    budget      numeric,
    spend       numeric,
    impressions integer,
    clicks      integer,
    conversions integer,
    revenue     numeric,
    created_at  timestamptz not null default now()
);

-- ============================================================================
-- Indexes on commonly queried fields
-- ============================================================================
create index if not exists idx_leads_email        on public.leads (email);
create index if not exists idx_leads_status       on public.leads (status);
create index if not exists idx_leads_lead_source  on public.leads (lead_source);

create index if not exists idx_lead_predictions_lead_id       on public.lead_predictions (lead_id);
create index if not exists idx_lead_predictions_lead_priority on public.lead_predictions (lead_priority);

create index if not exists idx_campaigns_campaign_id on public.campaigns (campaign_id);
create index if not exists idx_campaigns_channel      on public.campaigns (channel);
create index if not exists idx_campaigns_date         on public.campaigns (date);

-- ============================================================================
-- Row Level Security
-- ----------------------------------------------------------------------------
-- RLS is ENABLED on every table (deny by default). The backend/ML pipeline
-- bypasses RLS via the service-role client or the direct DATABASE_URL
-- connection, so it is unaffected. Browser (anon) clients are restricted to
-- the read/insert policies below. Fire these policies up as Supabase Auth
-- integration lands.
-- ============================================================================
alter table public.users           enable row level security;
alter table public.leads           enable row level security;
alter table public.lead_predictions enable row level security;
alter table public.recommendations enable row level security;
alter table public.campaigns       enable row level security;

-- Helper: is the current authenticated token an organization admin?
-- Uses security definer so the role check itself is not blocked by RLS.
create or replace function public.is_org_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
    select exists (
        select 1 from public.users
        where id = auth.uid() and role = 'admin'
    );
$$;

-- Helper: is the current authenticated token an admin or manager?
create or replace function public.is_org_manager()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
    select exists (
        select 1 from public.users
        where id = auth.uid() and role in ('admin', 'manager')
    );
$$;

-- users ----------------------------------------------------------------------
-- Users read/update their own profile; admins manage every user row.
-- Inserts and deletes are not granted to browser tokens (service role only).
create policy "users_select_self_or_admin"
    on public.users
    for select
    using (auth.uid() = id or public.is_org_admin());

create policy "users_update_self_or_admin"
    on public.users
    for update
    using (auth.uid() = id or public.is_org_admin())
    with check (auth.uid() = id or public.is_org_admin());

-- leads ----------------------------------------------------------------------
-- Signed-in users can read the pipeline and record new enquiries.
-- Only managers update existing leads (status changes etc.).
create policy "leads_select_authenticated"
    on public.leads
    for select
    to authenticated
    using (true);

create policy "leads_insert_authenticated"
    on public.leads
    for insert
    to authenticated
    with check (true);

create policy "leads_update_managers"
    on public.leads
    for update
    to authenticated
    using (public.is_org_manager());

-- lead_predictions -----------------------------------------------------------
-- Read-only for signed-in users; ML pipeline writes via the service role.
create policy "lead_predictions_select_authenticated"
    on public.lead_predictions
    for select
    to authenticated
    using (true);

-- recommendations ------------------------------------------------------------
-- Read-only for signed-in users; pipeline writes via the service role.
create policy "recommendations_select_authenticated"
    on public.recommendations
    for select
    to authenticated
    using (true);

-- campaigns ------------------------------------------------------------------
-- Read-only for signed-in users; campaign ingestion via the service role.
create policy "campaigns_select_authenticated"
    on public.campaigns
    for select
    to authenticated
    using (true);

-- ============================================================================
-- End of Decision-Intel schema migration. No seed data is inserted here.
-- ============================================================================