export const workspacePages = [
    { slug: 'prediction', label: 'Conversion Prediction', description: 'Score a stored lead using the trained conversion model.' },
    { slug: 'explainability', label: 'Explainable AI', description: 'Inspect SHAP contributions to an individual model prediction.' },
    { slug: 'segmentation', label: 'Customer Segmentation', description: 'Explore four behavioral clusters based on visits, email engagement, purchases, and loyalty.' },
    { slug: 'funnel', label: 'Funnel Analysis', description: 'Explore nested observed lead cohorts. These are not timestamped journey stages.' },
    { slug: 'attribution', label: 'Multi-Channel Attribution', description: 'Compare conversion credit across recorded channels. Each lead has one channel; multi-touch attribution requires journey data.' },
    { slug: 'campaigns', label: 'Campaign Analytics', description: 'Compare campaign types using stored lead outcomes and spend.' },
    { slug: 'optimization', label: 'Budget Optimization', description: 'Maximize estimated conversions under a budget and channel cap, or compare equal and efficiency-weighted allocations.' },
    { slug: 'simulator', label: 'What-If Simulator', description: 'Adjust channel budgets and estimate outcomes using historical conversion efficiency.' },
    { slug: 'recommendations', label: 'AI Recommendations', description: 'Review evidence-based rules derived from campaign metrics. Suggestions are not generated by a language model.' },
    { slug: 'reports', label: 'Reports', description: 'Review and export marketing summaries, channel performance, and campaign analytics.' },
    { slug: 'settings', label: 'Settings', description: 'Save your personal display preferences for the marketing workspace.' }
];
